name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 设置环境
      - uses: actions/setup-node@v3
        with:
          node-version: 10
          cache: npm
      # 安装hexo
      - name: Install hexo
        run: npm install hexo-cli -g
      # 安装依赖
      - name: Install dependencies
        run: npm install
      # 构建项目
      - name: Build website
        run: hexo deploy
      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: website
          publish_dir: ./blog
          user_name: hengboy
          user_email: jnyuqy@gmail.com
          cname: blog.minbox.org
